### ISSUE TITLE
Why isn't this done already?

### ISSUE THREAD

**Issue by joggerjoel** [mika314/KitchenSink#1]
I feel like this project shouldn't take more than 10 minutes to create...

**Comment by mika314** [comment]
Dear [Username],

Thank you for reaching out to us. We appreciate your feedback and interest in our project.

We understand that you may have expectations for the completion time of this project, but as an open source project, it can often take longer to complete due to various factors such as the complexity of the project, the number of contributors, and their availability.

We are doing our best to make progress and deliver high-quality games. If you have any suggestions or specific features you would like to see, please feel free to let us know. We are always open to feedback and will do our best to incorporate your suggestions into our project.

Thank you for your support and understanding.

Best regards,
[Your name]
